### ISSUE TITLE
Exception: android.hardware.usb.UsbDevice.getInterface(UsbDevice.java:232) has java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by terenceLuffy** [mik3y/usb-serial-for-android#136]
This Exception is not presented if I test it on Android 4.4.4, with the same source in Android 5.1 SDK 22, it throws this Exception. It seems that the usb device is connected, but no interface is found, please help!

```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
at android.hardware.usb.UsbDevice.getInterface(UsbDevice.java:232)
at com.hoho.android.usbserial.driver.FtdiSerialDriver$FtdiSerialPort.read(FtdiSerialDriver.java:281)
at com.hoho.android.usbserial.util.SerialInputOutputManager.step(SerialInputOutputManager.java:159)
at com.hoho.android.usbserial.util.SerialInputOutputManager.run(SerialInputOutputManager.java:141)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by terenceLuffy** [comment]
I found the reason in [here](https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars&groupby=&sort=&id=159897) , it is because of multiple usb device plug-in and only the last one is working well.
