### ISSUE TITLE
连续去读数据有几率程序卡死

### ISSUE THREAD

**Issue by LuckyLi706** [mik3y/usb-serial-for-android#266]
以下是卡死日志：
"pool-3-thread-1" prio=5 tid=31 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x13740000 self=0x7825327c00
  | sysTid=27384 nice=0 cgrp=default sched=0/0 handle=0x780d9db4f0
  | state=S schedstat=( 3857370351 1700855692 5717 ) utm=293 stm=92 core=1 HZ=100
  | stack=0x780d8d8000-0x780d8da000 stackSize=1041KB
  | held mutexes=
  kernel: (couldn't read /proc/self/task/27384/stack stderr:Permission denied)
  native: #00 pc 000000000001f2ec  /system/lib64/libc.so (syscall+28)
  native: #01 pc 00000000000dbd94  /system/lib64/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+148)
  native: #02 pc 000000000052974c  /system/lib64/libart.so (_ZN3artL12GoToRunnableEPNS_6ThreadE.llvm.3280960267+448)
  native: #03 pc 0000000000529ca8  /system/lib64/libart.so (art::JniMethodEndWithReference(_jobject*, unsigned int, art::Thread*)+32)
  at android.hardware.usb.UsbDeviceConnection.native_request_wait(Native method)
  at android.hardware.usb.UsbDeviceConnection.requestWait(UsbDeviceConnection.java:301)
  at com.shoukong.gds.manager.usb.dirver.CommonUsbSerialPort.read(CommonUsbSerialPort.java:161)
  at com.shoukong.gds.manager.usb.util.SerialInputOutputManager.step(SerialInputOutputManager.java:171)
  at com.shoukong.gds.manager.usb.util.SerialInputOutputManager.run(SerialInputOutputManager.java:153)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
  at java.lang.Thread.run(Thread.java:784)

**Comment by kai-morich** [comment]
Crashes like yours are typically caused by
- processes in strange states
- issues in some Android versions
- vendor specific Android modifications
Here looks like the first type
