### ISSUE TITLE
Control Transfer Failed

### ISSUE THREAD

**Issue by shgrg1712** [mik3y/usb-serial-for-android#332]
Hello Koi,
               I am very thankful to you for this library. This is very useful. I have created one application where I have attached one thermal sensor with android device and capturing temperature using serial connection. 

I am facing one issue so I need your help. 

Scenario
1. Android app which is running in kiosk mode.
2. Thermal sensor connected with application using OTG 
3. Driver class used to connect CdcAcmSerialDriver

Issue 
1. Connect thermal sensor with android app using otg with only sensor connected to OTG. Connection successful with receiving data.
2. Connect power supply with micro terminal of OTG.
3. Restart the android device. but before restart disconnect the connection.
4. On application start, reconnect the serial connection.

Issue :
TYPE 6 MESSAGE Exception in connect   TRACE java.io.IOException: controlTransfer failed
	at com.hoho.android.usbserial.driver.CdcAcmSerialDriver$CdcAcmSerialPort.sendAcmControlMessage(CdcAcmSerialDriver.java:2)
	at com.hoho.android.usbserial.driver.CdcAcmSerialDriver$CdcAcmSerialPort.setParameters(CdcAcmSerialDriver.java:3)
	at d.h.a.a.c.a(UsbSerialConnection.java:44)
	at d.h.a.a.c$a.onReceive(UsbSerialConnection.java:7)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1391)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6714)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

This state is not recoverable. I have tried to connect to device again. It is throwing same error again & again. Please help

**Comment by KeaganFerrao** [comment]
Hi, I am facing the same issue. After serial connection disconnect I get control transfer failed. And does not connect again at all. Then need to restart device.
