### ISSUE TITLE
Waiting for USB request failed Exception

### ISSUE THREAD

**Issue by sylwek845** [mik3y/usb-serial-for-android#424]
Hi, I'm getting the following exception

` java.io.IOException: Waiting for USB request failed
        at com.hoho.android.usbserial.driver.CommonUsbSerialPort.read(CommonUsbSerialPort.java:192)
        at com.hoho.android.usbserial.driver.CommonUsbSerialPort.read(CommonUsbSerialPort.java:157)
        at com.hoho.android.usbserial.util.SerialInputOutputManager.step(SerialInputOutputManager.java:224)
        at com.hoho.android.usbserial.util.SerialInputOutputManager.run(SerialInputOutputManager.java:202)
        at java.lang.Thread.run(Thread.java:920)
`
I'm getting this after calling `SerialInputOutputManager(port, this).start()` but noticed when I do this 
` val man = SerialInputOutputManager(port, this)
                Thread.sleep(500)
                    man.start()`

it won't crash for 500 mills and I can recieve the data. Do you have any idea what may cause the issue? My implementation is almost identical as the one in the example. Thanks

**Comment by sylwek845** [comment]
Closing the issue... my bad had 2 starts...
