### ISSUE TITLE
Every time the USB link is closed, an error log is printed

### ISSUE THREAD

**Issue by mengzhidaren** [mik3y/usb-serial-for-android#569]
D/UsbDeviceConnectionJNI( 4637): close
W/SerialInputOutputManager( 4637): Run ending due to exception: Connection closed
W/SerialInputOutputManager( 4637): java.io.IOException: Connection closed
W/SerialInputOutputManager( 4637): 	at com.hoho.android.usbserial.driver.CommonUsbSerialPort.testConnection(CommonUsbSerialPort.java:162)
W/SerialInputOutputManager( 4637): 	at com.hoho.android.usbserial.driver.FtdiSerialDriver$FtdiSerialPort.read(FtdiSerialDriver.java:156)
W/SerialInputOutputManager( 4637): 	at com.hoho.android.usbserial.util.SerialInputOutputManager.step(SerialInputOutputManager.java:225)
W/SerialInputOutputManager( 4637): 	at com.hoho.android.usbserial.util.SerialInputOutputManager.run(SerialInputOutputManager.java:203)
W/SerialInputOutputManager( 4637): 	at java.lang.Thread.run(Thread.java:761)

If the thread is closed after:

Run ending due to exception: Connection closed
                                                                                                    java.io.IOException: Connection closed
                                                                                                    	at com.hoho.android.usbserial.driver.CommonUsbSerialPort.testConnection(CommonUsbSerialPort.java:162)
                                                                                                    	at com.hoho.android.usbserial.driver.FtdiSerialDriver$FtdiSerialPort.read(FtdiSerialDriver.java:156)
                                                                                                    	at com.hoho.android.usbserial.util.SerialInputOutputManager.step(SerialInputOutputManager.java:225)
                                                                                                    	at com.hoho.android.usbserial.util.SerialInputOutputManager.run(SerialInputOutputManager.java:203)
                                                                                                    	at java.lang.Thread.run(Thread.java:761)

**Comment by kai-morich** [comment]
I will check if it can be distinguished into normal close and real IO error
